-- Create the predictions table
CREATE TABLE predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unique_id TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  country TEXT NOT NULL,
  predictions JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE predictions ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to insert (since it's a public form)
-- Ideally, you'd want some captcha or rate limiting, but for now this works.
CREATE POLICY "Enable insert for all users" ON predictions
  FOR INSERT WITH CHECK (true);

-- Create a policy that allows reading only by unique_id (for the "My Prediction" page)
-- This is a bit tricky without auth, but we can allow reading if the user knows the unique_id.
-- However, for the admin page, we'll need a way to read all.
-- Since the admin page uses the same client key in this simple setup (anon key), 
-- we have to be careful.
-- A better approach for this simple app is to allow read access to everything 
-- BUT filter strictly on the client side or rely on the obscured unique_id.
-- For a truly secure admin, you should use Supabase Auth.
-- For now, to make the provided code work (which uses the anon key for everything):

CREATE POLICY "Enable read access for all users" ON predictions
  FOR SELECT USING (true);

-- Note: In a production environment with sensitive data, you should:
-- 1. Use Supabase Auth for the Admin page.
-- 2. Restrict the "Select" policy to only allow reading your own record (via unique_id match if possible, or auth uid).
-- 3. Use a Service Role key for the Admin operations (server-side).

-- Create an index on unique_id for faster lookups
CREATE INDEX predictions_unique_id_idx ON predictions (unique_id);
