import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const projectRoot = process.cwd();
const imagesDir = path.join(projectRoot, 'public', 'images');
const outFile = path.join(projectRoot, 'src', 'utils', 'lqipManifest.ts');

async function generateLqipForFile(filePath) {
  try {
    const buf = await sharp(filePath)
      .resize({ width: 24, withoutEnlargement: true })
      .webp({ quality: 30 })
      .toBuffer();
    const base64 = buf.toString('base64');
    return `data:image/webp;base64,${base64}`;
  } catch (err) {
    console.error('LQIP generation failed for', filePath, err.message);
    return '';
  }
}

async function main() {
  if (!fs.existsSync(imagesDir)) {
    console.error('Images directory not found:', imagesDir);
    process.exit(1);
  }

  const manifest = {};

  async function walk(dir) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(fullPath);
        continue;
      }
      if (!entry.isFile()) continue;
      const ext = path.extname(entry.name).toLowerCase();
      if (!['.webp', '.jpg', '.jpeg', '.png'].includes(ext)) continue;
      // skip auto-generated variant files
      const baseName = path.basename(entry.name, ext);
      if (/-(640|1024|1600)$/.test(baseName)) continue;

      // Prefer using the -640.webp variant for stable decoding; fallback to original
      const relPath = path.relative(imagesDir, fullPath).replace(/\\/g, '/');
      const baseNoExt = path.join(path.dirname(fullPath), path.basename(entry.name, ext));
      const preferred640 = `${baseNoExt}-640.webp`;
      const sourceForLqip = fs.existsSync(preferred640) ? preferred640 : fullPath;
      const lqip = await generateLqipForFile(sourceForLqip);
      if (lqip) {
        const key = `/images/${relPath}`;
        manifest[key] = lqip;
      }
    }
  }

  await walk(imagesDir);

  const ts = [
    '// Auto-generated by scripts/generate-lqip.mjs. Do not edit manually.',
    'export const lqipManifest: Record<string, string> = ' + JSON.stringify(manifest, null, 2) + ';',
    '',
  ].join('\n');

  fs.writeFileSync(outFile, ts, 'utf8');
  console.log(`Wrote LQIP manifest to ${outFile} with ${Object.keys(manifest).length} entries.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});