import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const projectRoot = process.cwd();
const imagesDir = path.join(projectRoot, 'public', 'images');
const outFile = path.join(projectRoot, 'src', 'utils', 'lqipManifest.ts');

async function generateLqipForFile(filePath) {
  try {
    const buf = await sharp(filePath)
      .resize({ width: 24, withoutEnlargement: true })
      .webp({ quality: 30 })
      .toBuffer();
    const base64 = buf.toString('base64');
    return `data:image/webp;base64,${base64}`;
  } catch (err) {
    console.error('LQIP generation failed for', filePath, err.message);
    return '';
  }
}

async function main() {
  if (!fs.existsSync(imagesDir)) {
    console.error('Images directory not found:', imagesDir);
    process.exit(1);
  }

  const entries = fs.readdirSync(imagesDir, { withFileTypes: true });
  const manifest = {};

  for (const entry of entries) {
    if (!entry.isFile()) continue;
    const ext = path.extname(entry.name).toLowerCase();
    if (ext !== '.webp' && ext !== '.jpg' && ext !== '.jpeg' && ext !== '.png') continue;
    const fullPath = path.join(imagesDir, entry.name);
    const lqip = await generateLqipForFile(fullPath);
    if (lqip) {
      // key should match app usage paths like '/images/filename.webp'
      const key = `/images/${entry.name}`;
      manifest[key] = lqip;
    }
  }

  const ts = [
    '// Auto-generated by scripts/generate-lqip.mjs. Do not edit manually.',
    'export const lqipManifest: Record<string, string> = ' + JSON.stringify(manifest, null, 2) + ';',
    '',
  ].join('\n');

  fs.writeFileSync(outFile, ts, 'utf8');
  console.log(`Wrote LQIP manifest to ${outFile} with ${Object.keys(manifest).length} entries.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});